export type CountriesType = Record<string, string[]>

export type CountriesName = keyof typeof COUNTRIES

export const COUNTRIES: CountriesType = {
    Belarus: [
        'Minsk',
        'Gomel',
        'Mogilev',
        'Vitebsk',
        'Hrodna',
        'Brest',
        'Babruysk',
        'Baranovichi',
        'Borisov',
        'Pinsk',
        'Orsha',
        'Mazyr',
        'Salihorsk',
        'Lida',
        'Polotsk',
        'Novopolotsk',
        'Zhodino',
        'Slutsk',
        'Svetlogorsk',
        'Rahachow'
    ],
    Kazakhstan: [
        'Astana',
        'Almaty',
        'Shymkent',
        'Karaganda',
        'Aktobe',
        'Taraz',
        'Pavlodar',
        'Ust-Kamenogorsk',
        'Kyzylorda',
        'Semey',
        'Turkestan',
        'Atyrau',
        'Kostanay',
        'Petropavlovsk',
        'Oral',
        'Temirtau',
        'Aktau',
        'Taldykorgan',
        'Kokshetau',
        'Ekibastuz'
    ],
    Russia: [
        'Moscow',
        'Saint Petersburg',
        'Novosibirsk',
        'Yekaterinburg',
        'Nizhny Novgorod',
        'Kazan',
        'Chelyabinsk',
        'Omsk',
        'Samara',
        'Rostov-on-Don',
        'Ufa',
        'Krasnoyarsk',
        'Perm',
        'Voronezh',
        'Volgograd',
        'Krasnodar',
        'Saratov',
        'Tyumen',
        'Izhevsk',
        'Ulyanovsk'
    ],
    Poland: [
        'Warsaw',
        'Kraków',
        'Łódź',
        'Wrocław',
        'Poznań',
        'Gdańsk',
        'Szczecin',
        'Bydgoszcz',
        'Lublin',
        'Katowice',
        'Białystok',
        'Gdynia',
        'Częstochowa',
        'Radom',
        'Toruń',
        'Sosnowiec',
        'Kielce',
        'Rzeszów',
        'Gliwice',
        'Zabrze'
    ]
}
