export type CountriesType = Record<string, string[]>

export type CountriesNameEN = keyof typeof COUNTRIES_EN
export type CountriesNameRU = keyof typeof COUNTRIES_RU

export const COUNTRIES_EN: CountriesType = {
  Belarus: [
    'Minsk',
    'Gomel',
    'Mogilev',
    'Vitebsk',
    'Hrodna',
    'Brest',
    'Babruysk',
    'Baranovichi',
    'Borisov',
    'Pinsk',
    'Orsha',
    'Mazyr',
    'Salihorsk',
    'Lida',
    'Polotsk',
    'Novopolotsk',
    'Zhodino',
    'Slutsk',
    'Svetlogorsk',
    'Rahachow',
  ],
  Kazakhstan: [
    'Astana',
    'Almaty',
    'Shymkent',
    'Karaganda',
    'Aktobe',
    'Taraz',
    'Pavlodar',
    'Ust-Kamenogorsk',
    'Kyzylorda',
    'Semey',
    'Turkestan',
    'Atyrau',
    'Kostanay',
    'Petropavlovsk',
    'Oral',
    'Temirtau',
    'Aktau',
    'Taldykorgan',
    'Kokshetau',
    'Ekibastuz',
  ],
  Poland: [
    'Warsaw',
    'Kraków',
    'Łódź',
    'Wrocław',
    'Poznań',
    'Gdańsk',
    'Szczecin',
    'Bydgoszcz',
    'Lublin',
    'Katowice',
    'Białystok',
    'Gdynia',
    'Częstochowa',
    'Radom',
    'Toruń',
    'Sosnowiec',
    'Kielce',
    'Rzeszów',
    'Gliwice',
    'Zabrze',
  ],
  Russia: [
    'Moscow',
    'Saint Petersburg',
    'Novosibirsk',
    'Yekaterinburg',
    'Nizhny Novgorod',
    'Kazan',
    'Chelyabinsk',
    'Omsk',
    'Samara',
    'Rostov-on-Don',
    'Ufa',
    'Krasnoyarsk',
    'Perm',
    'Voronezh',
    'Volgograd',
    'Krasnodar',
    'Saratov',
    'Tyumen',
    'Izhevsk',
    'Ulyanovsk',
  ],
}

export const COUNTRIES_RU: CountriesType = {
  Беларусь: [
    'Минск',
    'Гомель',
    'Могилев',
    'Витебск',
    'Гродно',
    'Брест',
    'Бобруйск',
    'Барановичи',
    'Борисов',
    'Пинск',
    'Орша',
    'Мозырь',
    'Солигорск',
    'Лида',
    'Полоцк',
    'Новополоцк',
    'Жодино',
    'Слуцк',
    'Светлогорск',
    'Рогачев',
  ],
  Казахстан: [
    'Астана',
    'Алматы',
    'Шымкент',
    'Караганда',
    'Актобе',
    'Тараз',
    'Павлодар',
    'Усть-Каменогорск',
    'Кызылорда',
    'Семей',
    'Туркестан',
    'Атырау',
    'Костанай',
    'Петропавловск',
    'Уральск',
    'Темиртау',
    'Актау',
    'Талдыкорган',
    'Кокшетау',
    'Экибастуз',
  ],
  Польша: [
    'Варшава',
    'Краков',
    'Лодзь',
    'Вроцлав',
    'Познань',
    'Гданьск',
    'Щецин',
    'Быдгощ',
    'Люблин',
    'Катовице',
    'Белосток',
    'Гдыня',
    'Ченстохова',
    'Радом',
    'Торунь',
    'Сосновец',
    'Кельце',
    'Жешув',
    'Гливице',
    'Забже',
  ],
  Россия: [
    'Москва',
    'Санкт-Петербург',
    'Новосибирск',
    'Екатеринбург',
    'Нижний Новгород',
    'Казань',
    'Челябинск',
    'Омск',
    'Самара',
    'Ростов-на-Дону',
    'Уфа',
    'Красноярск',
    'Пермь',
    'Воронеж',
    'Волгоград',
    'Краснодар',
    'Саратов',
    'Тюмень',
    'Ижевск',
    'Ульяновск',
  ],
}
